version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - workout-network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - workout-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: workout_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: workout_user
      MYSQL_PASSWORD: workout_password
    ports:
      - "4200:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - workout-network

networks:
  workout-network:
    driver: bridge

volumes:
  mysql_data:
  